# docker-compose.yml
version: '3.8'

services:
  server:
    image: nginxdemos/hello
    ports: 
      - 80

  localtunnel:
    image: efrecon/localtunnel
    restart: on-failure
    command:
      --local-host server --port 80 --subdomain $SUBDOMAIN
    environment: 
      - SUBDOMAIN=ghcctest
    links:
      - server
    depends_on:
      - server